### ISSUE TITLE
Gaze Estimation Part

### ISSUE THREAD

**Issue by WuZhuoran** [shaoanlu/GazeML-keras#2]
Hi,

Thank you for sharing code. But in demo, you only generate 18 heatmaps of eyes.
How to calculate gaze directions via 18 heatmaps?

I found part of code which should be useful: https://github.com/swook/GazeML/blob/master/src/elg_demo.py#L174

**Comment by WuZhuoran** [comment]
This part of code may work:

```python
def calculate_gaze_vector(eye_landmarks):
    iris_centre = eye_landmarks[16, :]
    eyeball_centre = eye_landmarks[17, :]
    eyeball_radius = np.linalg.norm(eye_landmarks[18, :] -eye_landmarks[17, :])


    i_x0, i_y0 = iris_centre
    e_x0, e_y0 = eyeball_centre
    theta = -np.arcsin(np.clip((i_y0 - e_y0) / eyeball_radius, -1.0, 1.0))
    phi = np.arcsin(np.clip((i_x0 - e_x0) / (eyeball_radius * -np.cos(theta)),
                            -1.0, 1.0))
    current_gaze = np.array([theta, phi])
```

**Comment by keishatsai** [comment]
@WuZhuoran 
Hi
I am also wondering that, however, how do you get eye_landmarks[18] ..... since index is from 0 - 17?
Thanks

**Comment by WuZhuoran** [comment]
> @WuZhuoran
> Hi
> I am also wondering that, however, how do you get eye_landmarks[18] ..... since index is from 0 - 17?
> Thanks

eye_landmarks[18] is calculated from eye_radius.

**Comment by keishatsai** [comment]
@WuZhuoran 
Could you tell me which line is it? I couldn't find where exactly forms eye_landmarks[18] in the repo.
Thank you.

**Comment by WuZhuoran** [comment]
@keishatsai 

You can  check the original repo here: https://github.com/swook/GazeML/blob/master/src/elg_demo.py#L242

**Comment by pourfard** [comment]
@WuZhuoran As mentioned [issue](https://github.com/shaoanlu/GazeML-keras/issues/3) eye_radius is not implemented in Keras version. Have you estimated eye_radius from the Keras model? If yes, please tell me how?

**Comment by WuZhuoran** [comment]
@pourfard  According to paper, the eye_radius is output of the hourglass model.
So if you change the model with this output, it will be calculated.
