### ISSUE TITLE
Where is the output of `eye_radius`?

### ISSUE THREAD

**Issue by WuZhuoran** [shaoanlu/GazeML-keras#3]
Hi,

According to GazeML's Implementation, the output of network should be 18 heatmaps and 1 eye_radius. https://github.com/swook/GazeML/blob/master/src/models/elg.py#L123

Did you implement this in your keras model? 

Thank you!

**Comment by shaoanlu** [comment]
There is no radius regression branch in our Keras model as in the original ELG.
